### ISSUE TITLE
PRODUCT-RELEASE not supported in JSON output

### ISSUE THREAD

**Issue by remingtonc** [etingof/pysmi#23]
Will try to dig through pysmi internals and fix it eventually, wanted to file it regardless. :)  
Related to [jsondoc.py](https://github.com/etingof/pysmi/blob/master/pysmi/codegen/jsondoc.py#L877)

```bash
2018-04-05 15:40:21,526 pysmi: compiling CISCO-IETF-SCTP-EXT-CAPABILITY read from file:///Users/vinm/PycharmProjects/snmp_v2/mibs/CISCO-IETF-SCTP-EXT-CAPABILITY.my
Traceback (most recent call last):
  File "/Users/vinm/PycharmProjects/snmp_v2/snmp_v2.py", line 170, in <module>
    snmppop.transform_mibs_to_json()
  File "/Users/vinm/PycharmProjects/snmp_v2/snmp_v2.py", line 119, in transform_mibs_to_json
    ignoreErrors=True
  File "/Users/vinm/PycharmProjects/snmp_v2/venv/lib/python3.6/site-packages/pysmi/compiler.py", line 335, in compile
    textFilter=options.get('textFilter')
  File "/Users/vinm/PycharmProjects/snmp_v2/venv/lib/python3.6/site-packages/pysmi/codegen/jsondoc.py", line 940, in genCode
    self.handlersTable[declr[0]](self, self.prepData(declr[1:]))
  File "/Users/vinm/PycharmProjects/snmp_v2/venv/lib/python3.6/site-packages/pysmi/codegen/jsondoc.py", line 95, in prepData
    self.handlersTable[el[0]](self, self.prepData(el[1:]))
KeyError: 'PRODUCT-RELEASE'
```

ftp://ftp.cisco.com/pub/mibs/v2/CISCO-IETF-SCTP-EXT-CAPABILITY.my

**Comment by etingof** [comment]
Fixed by #24

**Comment by remingtonc** [comment]
@etingof Any chance of pushing the updated code in to pypi? Otherwise will just install via git.

**Comment by etingof** [comment]
Yes, I just wanted to merge [the MIB tossing tool](https://github.com/etingof/pysmi/tree/add-mibcomb-tool) into the upcoming release.

**Comment by etingof** [comment]
0.3.0 is out. Let's see if it breaks anything...? ;-)
